services:
  - type: worker
    name: usabocdelivery_bot
    runtime: python
    envVars: {}
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    pythonVersion: "3.11.9"
